"""
https://projecteuler.net/problem=2
Problem 2 - Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by
adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose
values do not exceed four million, find the sum of the
even-valued terms.
"""
#%%
def sum_even_fibonacci(maxNum):
    listEvenValues = [2]
    startValue = 1
    currentValue = 2
    while currentValue < maxNum:
        nextValue = startValue + currentValue
        if nextValue % 2 == 0:
            if nextValue < maxNum:
                print(nextValue)
                listEvenValues.append(nextValue)
        startValue = currentValue
        currentValue = nextValue
    return sum(listEvenValues)


sum_even_fibonacci(4000000)
# %%
